Analysis of covid19 cases using numpy:

In [73]:
import numpy as np

data=np.genfromtxt(
    "country_wise_latest.csv",
    delimiter=",",
    dtype=None,
    names=True,
    encoding="utf-8"
)




Assigning data to variables:

In [74]:
country= data["CountryRegion"]
confirmed= data["Confirmed"]
Deaths= data["Deaths"]
Recovered= data["Recovered"]
Active= data["Active"]


Mean of different data:

In [75]:
print("--MEAN--\n")
print(f"average confirmed cases: {confirmed.mean()}")
print(f"Average Deaths: {Deaths.mean()}")
print(f"Average recovered cases: {Recovered.mean()}")
print(f"Average active cases: {Active.mean()}")

--MEAN--

average confirmed cases: 88130.935828877
Average Deaths: 3497.51871657754
Average recovered cases: 50631.48128342246
Average active cases: 34001.935828877


Median of different data :

In [76]:
print("--MEDIAN--\n")
print(f"median confirmed cases: {np.median(confirmed)}")
print(f"median Deaths: {np.median(Deaths)}")
print(f"median recovered cases: {np.median(Recovered)}")
print(f"median active cases: {np.median(Active)}")

--MEDIAN--

median confirmed cases: 5059.0
median Deaths: 108.0
median recovered cases: 2815.0
median active cases: 1600.0


Standard Deviation of different data:

In [77]:
print("--STANDARD DEVIATION--\n")
print(f"std of confirmed cases: {confirmed.std()}")
print(f"std of Deaths: {Deaths.std()}")
print(f"std of recovered cases: {Recovered.std()}")
print(f"std of active cases: {Active.std()}")

--STANDARD DEVIATION--

std of confirmed cases: 382292.3737323721
std of Deaths: 14062.251403613142
std of recovered cases: 189678.9834023504
std of active cases: 212755.01793318504


Lowest,highest trends:


In [78]:
idx= np.argmax(Deaths)
max_death= Deaths[idx]
country_max= country[idx]
print(f" max no of deaths {max_death} occured in {country_max}")

idx2= np.argmin(Deaths)
min_death= Deaths[idx2]
country_min= country[idx2]
print(f" min no of deaths {min_death} occured in {country_min}")


 max no of deaths 148011 occured in US
 min no of deaths 0 occured in Bhutan


Countries with most deaths, least deaths

In [79]:
most_deaths= Deaths[Deaths>20000]
countries= country[Deaths>20000]

for death,nation in zip(most_deaths,countries):
    print(f"{nation}:{death}")

Brazil:87618
France:30212
India:33408
Italy:35112
Mexico:44022
Spain:28432
US:148011
United Kingdom:45844


In [80]:
least_deaths= Deaths[Deaths<5]
least_countries= country[Deaths<5]

for died,state in zip(least_deaths,least_countries):
    print(f"{state}:{died}")

Antigua and Barbuda:3
Belize:2
Bhutan:0
Botswana:2
Brunei:3
Burundi:1
Cambodia:0
Dominica:0
Eritrea:0
Fiji:0
Greenland:0
Grenada:0
Holy See:0
Laos:0
Liechtenstein:1
Monaco:4
Mongolia:0
Papua New Guinea:0
Saint Kitts and Nevis:0
Saint Lucia:0
Saint Vincent and the Grenadines:0
Seychelles:0
Timor-Leste:0
Uganda:2
Vietnam:0
Western Sahara:1


Multiple columns analysis:

In [81]:
print("countries with more deaths than recovered:")
print(f"{country[Deaths > Recovered]}\n")

print("countries whose recovery exceeds 1000 and deaths below 20 ")
mask= (Recovered>1000) & (Deaths < 20)
print(f"{country[mask]} ")

countries with more deaths than recovered:
['Canada' 'Mozambique' 'Netherlands' 'Serbia' 'Sweden' 'Syria'
 'United Kingdom']

countries whose recovery exceeds 1000 and deaths below 20 
['Iceland' 'Jordan' 'Maldives' 'Sri Lanka'] 


Correlation between different values:

In [82]:
corr_1= np.corrcoef(confirmed,Deaths)
corr_2= np.corrcoef(confirmed,Recovered)
corr_3= np.corrcoef(Recovered, Active)

print(f"the correlation between confirmed cases and Deaths is:\n {corr_1}")
print(f"the correlation between confirmed cases and recovered cases are:\n {corr_2}")
print(f"the correlation between Recovered cases and Active cases are:\n {corr_3}")

the correlation between confirmed cases and Deaths is:
 [[1.         0.93469843]
 [0.93469843 1.        ]]
the correlation between confirmed cases and recovered cases are:
 [[1.         0.90637675]
 [0.90637675 1.        ]]
the correlation between Recovered cases and Active cases are:
 [[1.         0.68210265]
 [0.68210265 1.        ]]
